#!/usr/bin/env bash

function kubens() {
	# Get sub command
	cmd="$1"
	if [ -z "$cmd" ]; then
		# If no command provided, treat as shorthand for show command
		kubens show
		return
	fi

	shift

	# Run sub command
	if [[ "$cmd" == "use" ]]; then
		# Namespace arg
		namespace="$1"
		if [ -z "$namespace" ]; then
			echo "Error: use sub-command requires the NAMESPACE argument" >&2
			return 1
		fi

		export KUBENS_NAMESPACE="$namespace"
		kubens show
	elif [[ "$cmd" == "show" ]]; then
		# If namespace is set
		if [ ! -z "$KUBENS_NAMESPACE" ]; then
			echo "Working in \"$KUBENS_NAMESPACE\" Kubernetes namespace"
		else
			# If no namespace set
			echo "No Kubernetes workspace set"
		fi
	elif [[ "$cmd" == "run" ]]; then
		# If a namespace is set
		if [ ! -z "$KUBENS_NAMESPACE" ]; then
			# Invoke kubectl with the namespace argument
			/usr/bin/env kubectl --namespace "$KUBENS_NAMESPACE" $@
		else
			# If no namespace set, do not invoke with the namespace argument
			/usr/bin/env kubectl $@
		fi
	elif [[ "$cmd" == "exit" ]]; then
		unset KUBENS_NAMESPACE
		echo "Kubernetes namespace unset"
	else
		# If no valid command is provided, treat as shorthand for
		# use command
		kubens use "$cmd"
	fi
}
